### ISSUE TITLE
Nginx redirect error

### ISSUE THREAD

**Issue by CruisingwIT** [tiredofit/docker-nginx#12]
### Summary
nginx Image redirect error

### Steps to reproduce
1. Start up a container with with NGINX_MODE=REDIRECT
2. Webpage return 404.

### What is the expected *correct* behavior?
Webpage should be redirected to the NGINX_REDIRECT_URL

### Relevant logs and/or screenshots
```
2022/07/07 02:19:39 [error] 1231#1231: *4 open() "/etc/nginx/<WEBROOT><REDIRECT_URL>" failed (2: No such file or directory), client: 0.0.ip.address, server: localhost, request: "GET / HTTP/1.1", host: "host.url.com"
```

### Environment

- Image version / tag:  tiredofit/nginx:latest
- Host OS: archlinux

**Comment by tiredofit** [comment]
Resolved in `6.1.5`
