### ISSUE TITLE
inotify support for NGINX_INCLUDE_CONFIGURATION file

### ISSUE THREAD

**Issue by juanluisbaptiste** [tiredofit/docker-nginx#3]
Hi David,

As I was dealing with the website's users with the transition from apache to nginx and how configuration works, the workflow has changed. Before, site editors could edit .htaccess directly to add redirects or any other configuration, I can fix that by using `NGINX_INCLUDE_CONFIGURATION=/www/wordpress/.htaccess.gninx` , but nginx still needs to be reloaded to read the updated configuration.

This could be fixed by using inotify to monitor the file pointed by `NGINX_INCLUDE_CONFIGURATION` and do an `nginx -s reload `when the file is modified.

This way I only need to help the editors team lo learn how to write the redirects for nginx instead of having to reload the sites every time a new configuration for a site needs to be updated.

What do you think ?

**Comment by tiredofit** [comment]
I can see that being useful as a configurable service. I can look into this starting Monday.

**Comment by tiredofit** [comment]
New Environment Variable `NGINX_RELOAD_ON_CONFIG_CHANGE` introduced in release 5.9.0 - Will take a bit for Docker Hub to build all the images that depend on this release. 2 days max.
 
It will reload if /etc/nginx/conf, /etc/nginx.conf.d/, /etc/nginx/conf.d/ and NGINX_INCLUDE_CONFIGURATION are updated. Hope this helps!

Let me know after you've tested so we can close this off.

**Comment by juanluisbaptiste** [comment]
Excellent !! I'm on vacations, I will test it next week when I get back.

Thanks.

**Comment by juanluisbaptiste** [comment]
I forgot to close this, thanks.
