### ISSUE TITLE
wrong param for access_log in site_optimization.conf

### ISSUE THREAD

**Issue by ldgabet** [tiredofit/docker-nginx#5]
Hello,

In the file "/etc/nginx/nginx.conf.d/site_optimization.conf"
every "access_log" are set to "on" or "off".

I think It should be a path, cause the logs are written in "/etc/nginx/on" instead.

**Comment by tiredofit** [comment]
Thank you for finding this. I'm actually going to remove the statement in line 22 entirely.

**Comment by tiredofit** [comment]
New release tagged as `tiredofit/nginx:5.9.4` - I'm building the variants now and Docker Hub will take over shortly thereafter to build any images dependent on it (notably `tiredofit/nginx-php-fpm` and others)

**Comment by ldgabet** [comment]
Issue fixed, thank you.
